baseurl = "https://chillingchakra.github.com"
languageCode = "en"
title = "N to the 9th Power"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/chillingchakra\">Chilling Chakra Productions</a> 2017"
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "N" # Author full name
authorEmail = "nicholai@sdf.org" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "N to the 9th Power" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = false # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.features]
disqusOnDemand = false  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "welcomeback_rr"
github = "chillingchakra"
email = "nicholai@sdf.org"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","twitter","email"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true